"use client";

// THESIS: the saved home is the shared centre of designing and agreeing.
// OWN-WORLD: navy/red, white task controls, open canvas and real model imagery.
// STORY: choose, describe, inspect, refine, compare, then agree on the same revision.
// FIRST VIEWPORT: compact project header, room rail, dominant canvas, one active task panel.
// FORM: a canvas-first Operate workspace in the existing VibeEstimate visual language.
import dynamic from "next/dynamic";
import Link from "next/link";
import Image from "next/image";
import { useRouter } from "next/navigation";
import { Component, useCallback, useEffect, useMemo, useRef, useState, type FormEvent, type ReactNode } from "react";
import { ArrowLeft, ArrowRight, Check, ChevronRight, Lightbulb, Plus, RotateCcw, Send, Sparkles } from "lucide-react";
import { applyDesignPatch, describeDesignChanges, designPlacements, homeTemplates, resolveDesignScope } from "@vibeestimate/scene-core";
import { catalog, designSelectionSchema, type DesignSelection, type HouseDocument, type HouseOperation, type HousePatch } from "@vibeestimate/scene-schema";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { makeHomeApi, type HomeProject, type HomeRevision, type HomeJob } from "@/lib/home-api";
import { clientAuth, usesEmulators, type SessionIdentity } from "@/lib/firebase";
import { makeRoomApi } from "@/lib/room-api";
import type { Room } from "@/lib/room-types";
import { RoomInvitation } from "@/components/room/room-invitation";
import { useHomeSession } from "./use-home-session";
import { HomeBrand } from "./home-workspace";
import { HousePlan } from "./house-plan";
import "./home-studio.css";

const HouseViewer = dynamic(() => import("@vibeestimate/pascal-adapter").then(module => module.HouseViewer), { ssr: false });
type PendingDesign = { origin: "design" | "chat"; requestId: string; prompt: string; selection: DesignSelection; baseRevisionId: string };
type View = "plan" | "overview" | "inside";
type Surface = "floor" | "body" | "front" | "back";
type Assistant = { id: string; name: string; introduction: string; instructions: string; createdAt: string };
type Agreement = { id: string; revisionId: string; title: string; markdown: string; createdAt: string; provider: "fixture" | "gemini"; model: string; status: "draft" };
type AssistantReply = { id: string; requestId: string; revisionId: string; text: string; changes: string[]; createdAt: string; provider: "fixture" | "gemini"; model: string; assistantId: string; status: "complete" | "conflict" };
type SharedHome = { assistantReplies: AssistantReply[]; job?: HomeJob; room: Room; home: HomeProject; role: "designer" | "client"; assistant: Assistant; decisions: { id: string; revisionId: string; role: "designer" | "client"; action: "accept" | "approve"; createdAt: string }[]; acceptedRevisionId: string | null; approvedRevisionId: string | null; agreements: Agreement[]; canAccept: boolean; canApprove: boolean; canGenerateAgreement: boolean };
const errorText = (cause: unknown) => cause instanceof Error ? cause.message : "This change could not be completed. Your saved design is still here.";
const prettyName = (value: string) => value.replaceAll("-", " ").replace(/^./, c => c.toUpperCase());
function itemLabel(scene: HouseDocument, id: string) {
  const item = scene.instances.find(instance => instance.id === id);
  if (!item) return scene.rooms.find(room => room.id === id)?.name ?? prettyName(id);
  return `${scene.rooms.find(room => room.id === item.roomId)?.name ?? "Room"} · ${catalog.find(entry => entry.id === item.catalogId)?.name ?? "Item"}`;
}
function designVersion(home: HomeProject, revisionId: string | null) {
  const index = home.revisions.findIndex(revision => revision.id === revisionId);
  return index < 0 ? "Saved design" : `Design version ${index + 1} · ${home.revisions[index].title}`;
}
function selectionLabel(scene: HouseDocument, selection: DesignSelection) {
  if (selection.kind === "home") return "Whole home";
  if (selection.kind === "room" || selection.kind === "region") return `${scene.rooms.find(room => room.id === selection.roomId)?.name ?? "Room"}${selection.kind === "region" ? " · selected area" : ""}`;
  if (selection.kind === "object") return itemLabel(scene, selection.entityId);
  if (selection.surface === "front" || selection.surface === "back") {
    const wall = scene.walls.find(item => item.id === selection.entityId), roomId = selection.surface === "front" ? wall?.frontRoomId : wall?.backRoomId;
    return `${scene.rooms.find(room => room.id === roomId)?.name ?? "Outside"} · wall face`;
  }
  return `${itemLabel(scene, selection.entityId)} · ${selection.surface === "floor" ? "floor" : "finish"}`;
}
class GraphicsBoundary extends Component<{ children: ReactNode; onFailure: () => void }, { failed: boolean }> {
  state = { failed: false };
  static getDerivedStateFromError() { return { failed: true }; }
  componentDidCatch() { this.props.onFailure(); }
  render() { return this.state.failed ? null : this.props.children; }
}
function ensureFinished(result: { home: HomeProject; job?: HomeJob }) { const job = result.job ?? result.home.activeJob; if (job && job.status !== "complete") throw new Error(job.error?.message ?? (job.status === "save_pending" ? "Your design is generated but needs a save status check. Your previous version is preserved." : "The assistant has not completed this request. Check its status before starting another.")); }
function download(blob: Blob, filename: string) { const url = URL.createObjectURL(blob), link = document.createElement("a"); link.href = url; link.download = filename; document.body.append(link); link.click(); link.remove(); setTimeout(() => URL.revokeObjectURL(url), 1000); }
function dataOf(event: FormEvent<HTMLFormElement>) { event.preventDefault(); return new FormData(event.currentTarget); }
function NumberField({ label, name, value, min, max }: { label: string; name: string; value: number; min?: number; max?: number }) { return <label className="home-field"><span>{label}</span><Input type="number" name={name} defaultValue={value} min={min} max={max} step="1" required /></label>; }

export function HomeStudio({ homeId = "", sharedRoomId, identity = "designer", initialRoom }: { homeId?: string; sharedRoomId?: string; identity?: SessionIdentity; initialRoom?: Room }) {
  const router = useRouter(), session = useHomeSession(identity), api = useMemo(() => makeHomeApi(identity, sharedRoomId), [identity, sharedRoomId]);
  const [home, setHome] = useState<HomeProject | null>(null), [loadedUid, setLoadedUid] = useState(""), [shared, setShared] = useState<SharedHome | null>(null), [room, setRoom] = useState<Room | null>(initialRoom ?? null);
  const [busy, setBusy] = useState(""), [error, setError] = useState(""), [notice, setNotice] = useState(""), [reload, setReload] = useState(0);
  const [selection, setSelection] = useState<DesignSelection>({ kind: "home" }), [roomFocus, setRoomFocus] = useState(""), [view, setView] = useState<View>("overview"), [lighting, setLighting] = useState<"day" | "evening">("day"), [panel, setPanel] = useState(sharedRoomId ? "share" : "design");
  const [pendingDesign, setPendingDesign] = useState<PendingDesign | null>(null);
  const [prompt, setPrompt] = useState(""), [message, setMessage] = useState(""), [comparison, setComparison] = useState<HomeRevision | null>(null), [redoId, setRedoId] = useState<string | null>(null);
  const [graphics, setGraphics] = useState<"loading" | "ready" | "failed">("loading"), [graphicsAttempt, setGraphicsAttempt] = useState(0), [reset, setReset] = useState(0), [assistant, setAssistant] = useState<Assistant | null>(null);
  const [inviteOpen, setInviteOpen] = useState(false), [inviteHref, setInviteHref] = useState(""), [joinCode, setJoinCode] = useState("");
  const pendingRef = useRef<PendingDesign | null>(null);
  const lock = useRef(false), requests = useRef(new Map<string, string>()), owner = useRef<string | null>(null), exportSvg = useRef<SVGSVGElement>(null), canvasColumn = useRef<HTMLElement>(null);
  const uid = session.user?.uid, connected = Boolean(uid && loadedUid === uid), current = connected ? home : null, scene = comparison?.scene ?? current?.scene;
  const focusedRoom = scene?.rooms.find(item => item.id === roomFocus) ?? scene?.rooms[0];
  const conversation = [...(room?.messages ?? []).map(item => ({ ...item, kind: "person" as const })), ...(shared?.assistantReplies ?? []).map(item => ({ ...item, kind: "assistant" as const }))].sort((a, b) => a.createdAt.localeCompare(b.createdAt) || a.id.localeCompare(b.id));
  const retryOrigin = panel === "design" ? "design" : panel === "share" && sharedRoomId ? "chat" : pendingDesign?.origin ?? "design";
  const id = current?.id ?? homeId, head = current?.headRevisionId, activeJob = current?.activeJob;
  const working = Boolean(busy || (activeJob && ["running", "save_pending"].includes(activeJob.status)));
  const unresolvedGeneration = Boolean(activeJob?.kind === "generate" && ["failed", "unknown", "cancelled", "conflict"].includes(activeJob.status));
  const shouldPoll = connected && Boolean(current) && Boolean(sharedRoomId || ["Generating design", "Preparing design summary", "Preparing draft agreement", "Assistant is designing"].includes(busy) || (activeJob && ["running", "save_pending", "unknown"].includes(activeJob.status)));
  const currentScene = current?.scene;
  const accept = useCallback((result: { home: HomeProject; job?: HomeJob }) => {
    if (clientAuth(identity).currentUser?.uid !== owner.current) return;
    const completed = result.job ?? result.home.activeJob;
    const pending = pendingRef.current;
    if (pending && completed?.requestId === pending.requestId && completed.status === "complete") {
      pendingRef.current = null; setPendingDesign(null);
      if (pending.origin === "chat") setMessage(previous => previous.trim() === pending.prompt ? "" : previous);
      else setPrompt(previous => previous.trim() === pending.prompt ? "" : previous);
      try { sessionStorage.removeItem('home-design:' + owner.current + ':' + result.home.id); } catch { /* Saved response remains authoritative. */ }
    }
    setHome(previous => previous && previous.updatedAt > result.home.updatedAt ? previous : previous?.headRevisionId === result.home.headRevisionId ? { ...result.home, scene: previous.scene } : result.home);
    if (result.home.scene) setSelection(previous => { try { resolveDesignScope(result.home.scene!, previous); return previous; } catch { return { kind: "home" }; } });
    if ("room" in result) { const next = result as SharedHome; setShared(next); setRoom(next.room); setAssistant(next.assistant); }
  }, [identity]);
  useEffect(() => {
    if (!uid) return; let alive = true; owner.current = uid;
    void api.get(homeId).then(async result => { if (alive && clientAuth(identity).currentUser?.uid === uid) { accept(result); setLoadedUid(uid); setError("");
      try {
        const stored = sessionStorage.getItem('home-design:' + uid + ':' + result.home.id);
        if (stored) {
          const parsed = JSON.parse(stored);
          if (typeof parsed.prompt === 'string' && parsed.prompt.length <= 2000 && typeof parsed.requestId === 'string' && typeof parsed.baseRevisionId === 'string') {
            const recovered: PendingDesign = { ...parsed, origin: parsed.origin === 'chat' ? 'chat' : 'design', selection: designSelectionSchema.parse(parsed.selection) };
            const firstRecovery = pendingRef.current?.requestId !== recovered.requestId;
            pendingRef.current = recovered; setPendingDesign(recovered);
            if (firstRecovery) { setSelection(recovered.selection); if (recovered.origin === "chat") setMessage(previous => previous || recovered.prompt); else setPrompt(previous => previous || recovered.prompt); }
            // Resolve this exact request, even if another request is now the active job.
            // GET never dispatches a model. A lost success retires its input instead of requeuing it.
            const checked = await api.job(result.home.id, recovered.requestId);
            if (alive && clientAuth(identity).currentUser?.uid === uid) accept({ home: checked.home ?? result.home, job: checked.job });
          }
        }
      } catch { if (alive) setNotice('A previous request needs a status check. Your saved design is preserved.'); } } }).catch(cause => { if (alive) { setLoadedUid(uid); setError(errorText(cause)); } });
    return () => { alive = false; };
  }, [uid, api, homeId, reload, accept, identity]);
  useEffect(() => {
    if (!shouldPoll) return;
    let alive = true, polling = false;
    const timer = setInterval(() => { if (polling) return; polling = true; void api.get(id).then(result => { if (alive) accept(result); }).catch(() => { if (alive) setNotice("Connection interrupted. Your saved design is here; reconnecting…"); }).finally(() => { polling = false; }); }, 2500);
    return () => { alive = false; clearInterval(timer); };
  }, [shouldPoll, id, api, accept]);
  useEffect(() => { if (!prompt.trim() && !message.trim() && !busy) return; const warn = (event: BeforeUnloadEvent) => { event.preventDefault(); }; window.addEventListener("beforeunload", warn); return () => window.removeEventListener("beforeunload", warn); }, [prompt, message, busy]);
  const onReady = useCallback(() => setGraphics("ready"), []), onFailure = useCallback(() => setGraphics("failed"), []);
  function requestId(key: string, fresh = false) { const scoped = `${uid}:${id}:${head}:${key}`; let value = requests.current.get(scoped); if (!value || fresh) { value = crypto.randomUUID(); requests.current.set(scoped, value); } return value; }
  async function run(label: string, work: () => Promise<void>) { if (lock.current) return; lock.current = true; setBusy(label); setError(""); setNotice(""); try { await work(); } catch (cause) { if (clientAuth(identity).currentUser?.uid === owner.current) setError(errorText(cause)); } finally { lock.current = false; setBusy(""); } }
  async function mutate(operations: HouseOperation[], selected = selection) {
    if (!current?.scene || !head || comparison || working) return;
    const patch: HousePatch = { schemaVersion: 2, operations };
    await run("Saving change", async () => { applyDesignPatch(current.scene!, patch, selected); const result = await api.revise(id, patch, structuredClone(selected), head, requestId(JSON.stringify({ patch, selected }))); accept(result); setRedoId(null); setNotice("Change saved. Earlier versions are preserved."); });
  }
  function rememberAttempt(attempt: PendingDesign | null) {
    pendingRef.current = attempt; setPendingDesign(attempt);
    try { const key = 'home-design:' + uid + ':' + id; if (attempt) sessionStorage.setItem(key, JSON.stringify(attempt)); else sessionStorage.removeItem(key); }
    catch { setNotice('This browser cannot keep request recovery across reloads. Keep this page open until the request finishes.'); }
  }
  async function generate(retry = false) {
    if (!head || comparison || working || (!retry && unresolvedGeneration)) return;
    const origin = retry ? retryOrigin : "design";
    const input = (origin === "chat" ? message : prompt).trim();
    if (!input) return;
    const scope = structuredClone(selection);
    const attempt: PendingDesign = { origin, prompt: input, selection: scope, baseRevisionId: head, requestId: requestId('generate:' + input + ':' + JSON.stringify(scope), retry) };
    await run('Generating design', async () => {
      rememberAttempt(attempt);
      const result = origin === "chat" && sharedRoomId ? await api.request<SharedHome>(`/api/rooms/${sharedRoomId}/home/messages`, { text: input, requestId: attempt.requestId, askAssistant: true, baseRevisionId: head, selection: scope }) : await api.generate(id, input, scope, head, attempt.requestId);
      accept(result); ensureFinished(result); rememberAttempt(null);
      if (origin === 'chat') setMessage(previous => previous.trim() === input ? '' : previous); else setPrompt(previous => previous.trim() === input ? '' : previous); setRedoId(null);
      setNotice('Your generated design is saved. Explore it, or make another change.');
    });
  }
  async function restore(revisionId: string, undo = false) { if (!head || working) return; await run("Saving restored design", async () => { const result = await api.restore(id, revisionId, head, requestId(`restore:${revisionId}`)); accept(result); setComparison(null); setRedoId(undo ? head : null); setNotice("Restored as a new saved version. Your earlier designs are preserved."); }); }
  async function inspectRevision(revisionId: string, reveal = false) { await run("Opening saved design", async () => { const result = await api.revision(id, revisionId); setComparison(result.revision); setNotice("Viewing a saved version. Your current design is preserved."); if (reveal) { canvasColumn.current?.focus({ preventScroll: true }); canvasColumn.current?.scrollIntoView({ behavior: "auto", block: "start" }); } }); }
  function choose(entityId: string, surface?: Surface) {
    if (!scene || comparison) return;
    const item = scene.instances.find(item => item.id === entityId), chosenRoom = scene.rooms.find(item => item.id === entityId), wall = scene.walls.find(item => item.id === entityId);
    if (item) { setSelection({ kind: "object", entityId }); setRoomFocus(item.roomId); }
    else if (chosenRoom) { setSelection(surface === "floor" ? { kind: "surface", entityId, surface } : { kind: "room", roomId: entityId }); setRoomFocus(entityId); }
    else if (wall) { setSelection({ kind: "surface", entityId, surface: surface === "back" ? "back" : "front" }); }
    else { setNotice("Doors and windows are part of this starting floor plan. Select a room, furnishing or finish to design it."); return; }
    setPanel("edit");
  }
  function chooseArea(value: string) { setSelection(value === "home" ? { kind: "home" } : { kind: "room", roomId: value.slice(5) }); if (value !== "home") setRoomFocus(value.slice(5)); }
  async function exportPlan() {
    await run("Preparing floor plan", async () => { if (!exportSvg.current || !scene || !current) return; const exportedTitle = comparison?.title ?? current.title; const exportedVersion = current.revisions.findIndex(revision => revision.id === (comparison?.id ?? head)) + 1; const svg = exportSvg.current.cloneNode(true) as SVGSVGElement; svg.setAttribute("width", "1600"); svg.setAttribute("height", "1200"); const url = URL.createObjectURL(new Blob([new XMLSerializer().serializeToString(svg)], { type: "image/svg+xml" })); try { const picture = new window.Image(); await new Promise<void>((resolve, reject) => { picture.onload = () => resolve(); picture.onerror = () => reject(new Error("The floor plan could not be prepared.")); picture.src = url; }); const canvas = document.createElement("canvas"); canvas.width = 1600; canvas.height = 1200; const context = canvas.getContext("2d"); if (!context) throw new Error("Your browser could not prepare this image."); context.fillStyle = "#f4f6f8"; context.fillRect(0, 0, 1600, 1200); context.drawImage(picture, 0, 0, 1600, 1200); const blob = await new Promise<Blob>((resolve, reject) => canvas.toBlob(value => value ? resolve(value) : reject(new Error("Could not export the plan.")), "image/png")); download(blob, `${exportedTitle}-design-v${exportedVersion || "saved"}-floor-plan.png`); setNotice(`${designVersion(current, comparison?.id ?? head ?? null)} floor plan downloaded.`); } finally { URL.revokeObjectURL(url); } });
  }
  const scope = useMemo(() => { if (!scene) return { selectedIds: [] as string[] }; try { return resolveDesignScope(scene, selection); } catch { return { selectedIds: [] as string[] }; } }, [scene, selection]);
  // A whole-home selection authorizes generation without covering the entire model in highlights.
  const highlighted = selection.kind === "home" ? [] : selection.kind === "room" ? [selection.roomId] : scope.selectedIds;
  const selectedItem = scene && (selection.kind === "object" || selection.kind === "surface") ? scene.instances.find(item => item.id === selection.entityId) : undefined;
  const selectedSurface = selection.kind === "surface" ? selection.surface : selectedItem ? "body" as const : selection.kind === "room" ? "floor" as const : null;
  const selectedEntity = selection.kind === "object" || selection.kind === "surface" ? selection.entityId : selection.kind === "room" ? selection.roomId : null;
  const placements = useMemo(() => { if (!currentScene || comparison || panel !== "edit" || !["room", "region"].includes(selection.kind)) return []; try { return designPlacements(currentScene, selection); } catch { return []; } }, [currentScene, selection, comparison, panel]);
  const [assetId, setAssetId] = useState("floor-lamp");
  const placement = placements.find(candidate => candidate.instance.catalogId === assetId), selectedAsset = catalog.find(entry => entry.id === assetId) ?? catalog[0];
  const currentRevision = current?.revisions.find(revision => revision.id === head), parentId = currentRevision?.parentRevisionId, firstRevision = current?.revisions.find(revision => !revision.parentRevisionId);
  const template = homeTemplates.find(item => item.id === current?.templateId);
  const designAreaValue = selection.kind === "home" ? "home" : selection.kind === "room" || selection.kind === "region" ? `room:${selection.roomId}` : "selection";
  const editValue = selection.kind === "object" ? `object:${selection.entityId}` : selection.kind === "surface" ? `${selection.surface}:${selection.entityId}` : "";
  const sharedPath = sharedRoomId ? `/api/rooms/${encodeURIComponent(sharedRoomId)}/home` : "";

  if (!current) return <div className="home-product"><header className="home-header"><HomeBrand /><Link href="/">Your homes</Link></header><main className="home-connection"><h1>{!session.ready || (uid && loadedUid !== uid) ? "Opening your home…" : "This home could not open."}</h1><p>{error || session.error || "Connecting to your saved design."}</p>{session.ready && <Button onClick={() => { if (!session.user) void session.reconnect(); else setReload(value => value + 1); }}>Reconnect</Button>}</main></div>;
  if (!current.scene || !scene || !focusedRoom) return <div className="home-product"><header className="home-header"><HomeBrand /><Link href="/">Your homes</Link></header><main className="home-library home-template-page"><Link href="/" className="home-back" aria-label="Your homes"><ArrowLeft size={17} aria-hidden="true" />Your homes</Link><h1>Choose a starting home</h1><p>Start with the shape that suits you. Your assistant will help with the furniture, lighting and finishes.</p>{error && <div role="alert" className="home-error">{error}</div>}<div className="home-template-grid">{homeTemplates.map(item => <article key={item.id}><Image src={item.thumbnailPath} width={960} height={700} alt={`${item.name}, a complete single-floor layout`} priority /><div><h2>{item.name}</h2><p>{item.description}</p><span>{item.bedrooms} bedroom{item.bedrooms > 1 ? "s" : ""} · {item.areaM2} m² · {item.roomCount} rooms</span><Button disabled={!!busy} onClick={() => void run("Saving starting home", async () => { const result = await api.template(id, item.id, current.headRevisionId, requestId(`template:${item.id}`)); accept(result); setNotice("Starting home saved. Tell your assistant what you’d like to change."); })}>Choose {item.name}<ArrowRight size={17} aria-hidden="true" /></Button></div></article>)}</div><p className="home-small">Authored concept layouts with measured furniture. Dimensions describe these templates; verify them against your own home before ordering or building.</p></main></div>;

  return <div className="home-product home-studio" data-home-id={current.id} data-revision-id={current.headRevisionId}>
    <a className="skip-link" href="#design-workspace">Skip to design workspace</a>
    <header className="home-header home-studio-header"><HomeBrand /><div className="home-project-title"><h1>{current.title}</h1><span role="status">{busy || (activeJob?.status === "running" ? "Generating design" : activeJob?.status === "save_pending" ? "Waiting to save" : "Saved")}{!busy && (!activeJob || activeJob.status === "complete") && <Check size={13} aria-hidden="true" />}</span></div><Link href="/" className="home-back" aria-label="Your homes"><ArrowLeft size={16} aria-hidden="true" /><span>Your homes</span></Link></header>
    <main id="design-workspace" className="home-design-layout">
      <aside className="home-room-rail" aria-label="Rooms"><h2>Rooms</h2><Button variant="ghost" aria-pressed={selection.kind === "home"} onClick={() => chooseArea("home")}>Whole home</Button>{scene.rooms.map(item => <Button variant="ghost" key={item.id} aria-pressed={selection.kind === "room" && selection.roomId === item.id} onClick={() => chooseArea(`room:${item.id}`)}><span>{item.name}</span><small>{(item.width * item.depth / 1e6).toFixed(1)} m²</small></Button>)}<div className="home-rail-note"><strong>{template?.areaM2 ?? (scene.rooms.reduce((sum, item) => sum + item.width * item.depth, 0) / 1e6).toFixed(1)} m²</strong><span>Single floor · {scene.rooms.length} rooms</span><span>Ceiling {scene.level.ceilingHeight / 1000} m · assumed</span></div></aside>
      <section ref={canvasColumn} tabIndex={-1} className="home-canvas-column" aria-label="Home design">
        <div className="home-view-toolbar"><div role="group" aria-label="House view">{(["plan", "overview", "inside"] as const).map(mode => <Button key={mode} variant="ghost" aria-pressed={view === mode} onClick={() => { if (view === "plan" && mode !== "plan") setGraphics("loading"); setView(mode); }}>{prettyName(mode)}</Button>)}</div><div className="home-view-actions"><Button variant="ghost" aria-pressed={lighting === "evening"} disabled={view === "plan"} onClick={() => setLighting(value => value === "day" ? "evening" : "day")}><Lightbulb size={16} aria-hidden="true" />{lighting === "day" ? "Evening" : "Day"}</Button><Button variant="ghost" aria-label="Reset view" disabled={view === "plan"} onClick={() => setReset(value => value + 1)}><RotateCcw size={17} aria-hidden="true" /></Button></div></div>
        {view === "inside" && <label className="home-inside-room"><span>Inside room</span><select value={focusedRoom.id} onChange={event => { setRoomFocus(event.target.value); setReset(value => value + 1); }}>{scene.rooms.map(item => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label>}
        {comparison && <div className="home-comparison-banner"><div><strong>{comparison.title}</strong><span>Saved {new Date(comparison.createdAt).toLocaleString("en-IN")} · comparison view</span><details><summary>Changes in your current design</summary><ul>{describeDesignChanges(comparison.scene, current.scene).map((change, i) => <li key={i}>{change}</li>)}</ul></details></div><Button variant="outline" onClick={() => { setComparison(null); setNotice("Current design restored in the same view."); }}>Return to current design</Button></div>}
        <div className="home-canvas" data-view={view} aria-label={`${view} of ${scene.name}`}>
          {view === "plan" ? <HousePlan document={scene} selectedIds={highlighted} region={scope.region} onSelect={choose} /> : <>
            {graphics !== "failed" && <GraphicsBoundary key={graphicsAttempt} onFailure={onFailure}><HouseViewer document={scene} mode={view} roomId={focusedRoom.id} lighting={lighting} reset={reset} selectedIds={highlighted} onSelect={choose} onReady={onReady} onFailure={onFailure} /></GraphicsBoundary>}
            {graphics === "loading" && <div className="home-canvas-loading" role="status"><div className="home-loading"><div /><div /></div><strong>Opening your home</strong><span>Preparing the 3D view…</span></div>}
            {graphics === "failed" && <div className="home-graphics-fallback"><HousePlan document={scene} /><div role="alert"><h2>3D is unavailable on this device</h2><p>Your saved home and Plan editing are ready to use.</p><Button onClick={() => setView("plan")}>Open Plan</Button><Button variant="outline" onClick={() => { setGraphics("loading"); setGraphicsAttempt(value => value + 1); }}>Retry 3D</Button></div></div>}
          </>}
          <div className="home-canvas-caption"><span>{view === "inside" ? focusedRoom.name : "Your home"}</span><span>{scene.instances.length} furnishings · {scene.instances.filter(item => item.light?.enabled).length} lights on</span></div>
        </div>
        <div className="home-canvas-foot"><p>{view === "plan" ? "Select a room, wall face or object. Dimensions in millimetres." : view === "inside" ? "Drag to look around. Reset returns to eye level." : "Drag to orbit. Select an object to refine it."}</p><div>{!sharedRoomId && <><Button variant="ghost" disabled={!parentId || working || !!comparison || !!sharedRoomId} onClick={() => parentId && void restore(parentId, true)}>Undo</Button><Button variant="ghost" disabled={!redoId || working || !!comparison || !!sharedRoomId} onClick={() => redoId && void restore(redoId)}>Redo</Button></>}</div></div>
        <p className="home-lighting-note">Concept design · illustrative lighting without wall occlusion. Check dimensions and specifications before ordering.</p>
        {notice && <p className="home-notice" role="status">{notice}</p>}{error && <div className="home-error" role="alert"><strong>We couldn’t finish that change.</strong><p>{error}</p><Button variant="outline" onClick={() => setReload(value => value + 1)}>Check saved design</Button></div>}
        {activeJob && ["failed", "unknown", "save_pending", "conflict", "cancelled"].includes(activeJob.status) && <div className="home-job-note" role="status"><strong>{activeJob.status === "unknown" ? "Generation needs a status check" : activeJob.status === "conflict" ? "Another version was saved" : activeJob.status === "save_pending" ? "Design generated · saving needs attention" : "Generation did not complete"}</strong><p>{activeJob.error?.message ?? "Your last saved design is preserved."}</p><Button variant="outline" onClick={() => setReload(value => value + 1)}>Check generation status</Button>{activeJob.status === "save_pending" && <Button variant="outline" disabled={!!busy} onClick={() => void run("Finishing saved design", async () => { const result = await api.resume(id, activeJob.requestId); accept(result); ensureFinished(result); rememberAttempt(null); setNotice("Your generated result is saved. No new model call was made."); })}>Finish saving</Button>}{unresolvedGeneration && <><p>{activeJob.status === "unknown" ? "A new request makes another model attempt. The earlier outcome stays recorded and cannot silently replace this design." : "Retry starts one new bounded attempt and preserves the previous request."}</p><Button variant="outline" disabled={working || !!comparison || !(retryOrigin === "chat" ? message : prompt).trim()} onClick={() => void generate(true)}>{activeJob.status === "unknown" ? "Start a new design request" : "Retry design"}</Button></>}</div>}
      </section>
      <aside className="home-task-panel" aria-label="Design tools"><Tabs value={panel} onValueChange={setPanel}><TabsList aria-label="Design tools"><TabsTrigger value="design">Design</TabsTrigger><TabsTrigger value="edit">Edit</TabsTrigger><TabsTrigger value="options">Options</TabsTrigger><TabsTrigger value="share">{sharedRoomId ? "Together" : "Share"}</TabsTrigger></TabsList>
        <div className="home-selection-control"><label className="home-field"><span>Design area</span><select aria-label="Design area" value={designAreaValue} onChange={event => chooseArea(event.target.value)}><option value="home">Whole home</option>{scene.rooms.map(item => <option key={item.id} value={`room:${item.id}`}>{item.name}</option>)}{designAreaValue === "selection" && <option value="selection">{selectionLabel(scene, selection)}</option>}</select></label>{selection.kind !== "home" && <p>{selectionLabel(scene, selection)} · changes stay in this selection</p>}</div>
        <TabsContent value="design"><div className="home-panel-heading"><Sparkles size={21} aria-hidden="true" /><div><h2>{assistant?.name ?? "Your design assistant"}</h2><p>Describe what you’d like to feel, see or change.</p></div></div>
          <form onSubmit={event => { event.preventDefault(); void generate(); }}><label className="home-field"><span>Describe your design</span><Textarea aria-label="Describe your design" value={prompt} onChange={event => setPrompt(event.target.value)} maxLength={2000} rows={5} placeholder="Add warm lights and a small table for relaxed evenings…" disabled={!!comparison} /></label><Button type="submit" className="home-full-action" disabled={!prompt.trim() || working || unresolvedGeneration || !!comparison}><Sparkles size={17} aria-hidden="true" />{busy === "Generating design" ? "Generating design…" : "Generate design"}</Button></form>
          {working && activeJob && <div className="home-generation-progress" role="status"><strong>{activeJob.phase === "planning" ? "Choosing furniture and finishes" : activeJob.phase === "validating" ? "Checking the design fits" : activeJob.phase === "saving" ? "Saving your design" : "Finishing your design"}</strong><p>You can keep exploring while the assistant works.</p>{!sharedRoomId && <Button variant="outline" onClick={() => void api.cancel(id, activeJob.requestId).then(result => { accept(result); setNotice("Generation cancelled. Your saved design is preserved."); }).catch(cause => setError(errorText(cause)))}>Cancel generation</Button>}</div>}
          <div className="home-prompt-ideas"><h3>A place to start</h3>{(template?.prompts ?? ["Add warm lights throughout the home.", "Make the living room comfortable for an evening together."]).map(text => <Button variant="ghost" key={text} onClick={() => setPrompt(text)} disabled={working || !!comparison}><span>{text}</span><ArrowRight size={16} aria-hidden="true" /></Button>)}</div>
          {current.brief && <section className="home-design-note"><h3>{current.brief.source === "template" ? "Your starting point" : "What changed"}</h3><p>{current.brief.summary}</p><span>{current.brief.source === "fixture" ? "Local test response · Gemini not connected" : current.brief.source === "gemini" ? "Generated with Gemini · validated and saved" : "Authored starting layout"}</span>{current.brief.assumptions.length > 0 && <details><summary>Design assumptions</summary><ul>{current.brief.assumptions.map((text, i) => <li key={i}>{text}</li>)}</ul></details>}</section>}
        </TabsContent>
        <TabsContent value="edit"><h2>Make it precise</h2><p className="home-small">Select on the plan or use the list. Each change saves a version.</p><label className="home-field"><span>Edit selection</span><select aria-label="Edit selection" value={editValue} onChange={event => { const [kind, ...rest] = event.target.value.split(":"); const entityId = rest.join(":"); if (!entityId) return; if (kind === "object") choose(entityId); else choose(entityId, kind as Surface); }}><option value="">Choose a furnishing or surface</option><optgroup label="Furniture and lights">{scene.instances.map(item => <option key={item.id} value={`object:${item.id}`}>{itemLabel(scene, item.id)}</option>)}</optgroup><optgroup label="Floors">{scene.rooms.map(item => <option key={item.id} value={`floor:${item.id}`}>{item.name} · floor</option>)}</optgroup><optgroup label="Wall faces">{scene.walls.flatMap((wall, index) => (["front", "back"] as const).map(side => { const roomId = side === "front" ? wall.frontRoomId : wall.backRoomId; return <option key={`${wall.id}-${side}`} value={`${side}:${wall.id}`}>{scene.rooms.find(item => item.id === roomId)?.name ?? "Outside"} · wall {index + 1} · {side}</option>; }))}</optgroup></select></label>
          {selectedItem && <section className="home-edit-section"><div className="home-selected-item"><Image src={catalog.find(entry => entry.id === selectedItem.catalogId)!.thumbnailPath} width={72} height={72} alt={catalog.find(entry => entry.id === selectedItem.catalogId)!.name} /><div><h3>{catalog.find(entry => entry.id === selectedItem.catalogId)?.name}</h3><p>{selectedItem.dimensions.join(" × ")} mm</p>{selectedItem.locked && <span>Locked · protected from changes</span>}</div></div>
            {selectedItem.light && <form key={`light-${selectedItem.id}-${head}`} onSubmit={event => { const data = dataOf(event); void mutate([{ op: "setLight", entityId: selectedItem.id, light: { enabled: data.get("enabled") === "on", intensity: Number(data.get("intensity")), temperature: String(data.get("temperature")) as "warm" | "neutral" | "cool" } }]); }}><h3>Light settings</h3><label className="home-check"><input type="checkbox" name="enabled" defaultChecked={selectedItem.light.enabled} /><span>Light enabled</span></label><NumberField label="Light intensity" name="intensity" value={selectedItem.light.intensity} min={0} max={100} /><label className="home-field"><span>Light temperature</span><select aria-label="Light temperature" name="temperature" defaultValue={selectedItem.light.temperature}><option value="warm">Warm</option><option value="neutral">Neutral</option><option value="cool">Cool</option></select></label><Button variant="outline" disabled={working || !!comparison || selectedItem.locked}>Apply light settings</Button></form>}
            <details className="home-details"><summary>Position and size</summary><form key={`transform-${selectedItem.id}-${head}`} onSubmit={event => { const data = dataOf(event); void mutate([{ op: "move", entityId: selectedItem.id, position: [Number(data.get("x")), selectedItem.position[1], Number(data.get("z"))] }, { op: "rotate", entityId: selectedItem.id, rotation: Number(data.get("rotation")) }]); }}><div className="home-field-grid"><NumberField label="Position X (mm)" name="x" value={selectedItem.position[0]} /><NumberField label="Position Z (mm)" name="z" value={selectedItem.position[2]} /><NumberField label="Rotation (°)" name="rotation" value={selectedItem.rotation} min={0} max={359} /></div><Button variant="outline" disabled={working || !!comparison || selectedItem.locked}>Apply position</Button></form>{catalog.find(entry => entry.id === selectedItem.catalogId)?.resizable && <form key={`resize-${selectedItem.id}-${head}`} onSubmit={event => { const data = dataOf(event); void mutate([{ op: "resize", entityId: selectedItem.id, dimensions: [Number(data.get("width")), Number(data.get("height")), Number(data.get("depth"))] }]); }}><div className="home-field-grid"><NumberField label="Width (mm)" name="width" value={selectedItem.dimensions[0]} min={50} /><NumberField label="Height (mm)" name="height" value={selectedItem.dimensions[1]} min={50} /><NumberField label="Depth (mm)" name="depth" value={selectedItem.dimensions[2]} min={50} /></div><Button variant="outline" disabled={working || !!comparison || selectedItem.locked}>Apply size</Button></form>}</details><Button variant="ghost" className="home-remove" disabled={working || !!comparison || selectedItem.locked} onClick={() => void mutate([{ op: "remove", entityId: selectedItem.id }])}>Remove item</Button>
          </section>}
          {selectedSurface && selectedEntity && <form className="home-edit-section" key={`finish-${selectedEntity}-${selectedSurface}-${head}`} onSubmit={event => { const data = dataOf(event); void mutate([{ op: "setMaterial", entityId: selectedEntity, surface: selectedSurface, materialId: String(data.get("material")) }]); }}><h3>Finish</h3><label className="home-field"><span>Material</span><select aria-label="Material" name="material" defaultValue={selectedItem?.materialId ?? (selectedSurface === "floor" ? scene.rooms.find(item => item.id === selectedEntity)?.floorMaterialId : selectedSurface === "front" ? scene.walls.find(item => item.id === selectedEntity)?.frontMaterialId : scene.walls.find(item => item.id === selectedEntity)?.backMaterialId)}>{scene.materials.map(item => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label><Button variant="outline" disabled={working || !!comparison || selectedItem?.locked}>Apply material</Button></form>}
          <section className="home-edit-section"><h3>Add furniture or a light</h3>{!["room", "region"].includes(selection.kind) ? <p>Choose a room in Design area to find pieces that fit.</p> : <><label className="home-field"><span>Furniture or light</span><select aria-label="Furniture or light" value={assetId} onChange={event => setAssetId(event.target.value)}>{catalog.map(entry => <option key={entry.id} value={entry.id}>{entry.name}</option>)}</select></label><div className="home-selected-item"><Image src={selectedAsset.thumbnailPath} width={72} height={72} alt={selectedAsset.name} /><div><strong>{selectedAsset.name}</strong><p>{selectedAsset.dimensions.join(" × ")} mm</p></div></div><p>{placement ? "A position with enough space is ready. Refine it after adding." : "This piece has no clear position in the selected area. Try a smaller piece or another room."}</p><Button disabled={!placement || working || !!comparison} onClick={() => placement && void mutate([{ op: "place", instance: placement.instance }])}><Plus size={17} aria-hidden="true" />Add selected item</Button></>}</section>
          <details className="home-details"><summary>Select a precise Plan area</summary><p>Use millimetres within {focusedRoom.name}. Only fully contained objects belong to this area.</p><form key={`region-${focusedRoom.id}`} onSubmit={event => { const data = dataOf(event); const next: DesignSelection = { kind: "region", roomId: focusedRoom.id, x: Number(data.get("x")), z: Number(data.get("z")), width: Number(data.get("width")), depth: Number(data.get("depth")) }; try { resolveDesignScope(scene, next); setSelection(next); setView("plan"); setNotice("Plan area selected. Boundary-crossing objects stay unchanged."); } catch (cause) { setError(errorText(cause)); } }}><div className="home-field-grid"><NumberField label="Area X (mm)" name="x" value={focusedRoom.x} /><NumberField label="Area Z (mm)" name="z" value={focusedRoom.z} /><NumberField label="Area width (mm)" name="width" value={Math.floor(focusedRoom.width / 2)} min={50} /><NumberField label="Area depth (mm)" name="depth" value={Math.floor(focusedRoom.depth / 2)} min={50} /></div><Button variant="outline">Select Plan area</Button></form></details>
        </TabsContent>
        <TabsContent value="options"><h2>Your design history</h2><p className="home-small">Every change keeps the earlier design. Compare at the same camera angle.</p>{firstRevision && firstRevision.id !== head && <Button variant="outline" disabled={working} onClick={() => void inspectRevision(firstRevision.id)}>Compare starting layout</Button>}<ol className="home-history">{[...current.revisions].reverse().map((revision, index) => <li key={revision.id}><div><span>{revision.id === head ? "Current design" : revision.conflict ? "Preserved conflicting option" : `Saved version ${current.revisions.length - index}`}</span><h3>{revision.title}</h3><p>{revision.description}</p></div><div><Button variant="ghost" disabled={working || revision.id === head} onClick={() => void inspectRevision(revision.id)}>View version</Button>{!sharedRoomId && <Button variant="ghost" disabled={working || revision.id === head} onClick={() => void restore(revision.id)}>Use this version</Button>}</div></li>)}</ol>
          <section className="home-export-section"><h3>Bring the design with you</h3><p className="home-small">Floor-plan export: {designVersion(current, comparison?.id ?? head ?? null)}.</p><Button variant="outline" disabled={working} onClick={() => void exportPlan()}>Download floor plan</Button>{!sharedRoomId && <><Button disabled={working || !!comparison} onClick={() => head && void run("Preparing design summary", async () => { const result = await api.summary(id, head, requestId("summary")); accept(result); ensureFinished(result); setNotice("Design summary saved for this exact version."); })}>Prepare design summary</Button>{current.summary && current.summary.revisionId === head && <><h4>{current.summary.title}</h4><p>{current.summary.narrative}</p><Button variant="outline" disabled={working} onClick={() => head && void run("Preparing download", async () => download(new Blob([await api.export(id, head)], { type: "text/markdown" }), `${current.title}-design.md`))}>Download design summary</Button></>}</>}</section>
        </TabsContent>
        <TabsContent value="share">{!sharedRoomId ? current.roomId ? <><h2>Your shared design room</h2><p>Your client, assistant, conversation and saved agreements are together in this home’s room.</p><Button asChild><Link href={`/rooms/${current.roomId}`}>Open shared room<ArrowRight size={17} aria-hidden="true" /></Link></Button></> : <><h2>Design together</h2><p>Create your assistant, then invite your client into this same saved home. Chat, refine and agree on one version.</p><div className="home-assistant-preview"><Sparkles size={25} aria-hidden="true" /><h3>{assistant?.name ?? "Your home design assistant"}</h3><p>{assistant?.introduction ?? "I’ll help turn your ideas into a home you can both explore, using furniture, lights and finishes that fit."}</p><span>{assistant ? "Assistant created" : "Ready with a name, introduction and design instructions"}</span></div>{!assistant ? <Button disabled={working} onClick={() => void run("Creating design assistant", async () => { const result = await api.request<{ assistant: Assistant }>("/api/design-assistants", { requestId: requestId("assistant") }); setAssistant(result.assistant); setNotice("Your design assistant is ready. Create a shared room to invite your client."); })}>Create design assistant</Button> : <Button disabled={working} onClick={() => void run("Creating shared room", async () => { const result = await api.request<SharedHome & { inviteToken: string; joinCode: string }>(`/api/homes/${id}/room`, { requestId: requestId("room"), assistantId: assistant.id }); router.push(`/rooms/${result.room.id}`); })}>Create shared room<ArrowRight size={17} aria-hidden="true" /></Button>}<p className="home-small">The client sees the home, conversation and design decisions. Private scope and pricing records remain private.</p><details className="home-details"><summary>Scope & proposal</summary><p>Prepare an editable proposal from this saved design. The assistant supplies descriptions; confirmed prices remain your decision.</p><Button variant="outline" disabled={working || !!comparison} onClick={() => head && void run("Preparing proposal", async () => { const result = await api.proposal(id, head, requestId("proposal")); router.push(`/proposals?project=${result.project.id}`); })}>Prepare proposal</Button></details></> : shared && room ? <>
          <div className="home-together-heading"><h2>Design together</h2><span>{shared.role === "client" ? "Client view" : "Designer view"}</span></div><p>{shared.assistant.introduction}</p>
          {shared.role === "designer" && <RoomInvitation roomId={sharedRoomId} clientJoined={room.clientJoined} open={inviteOpen} inviteHref={inviteHref} joinCode={joinCode} busy={!!busy} local={usesEmulators} homeDesign notice={notice} error={error} onOpenChange={() => setInviteOpen(value => !value)} onCreate={() => void run("Creating invitation", async () => { const result = await makeRoomApi(identity).invite(sharedRoomId); const url = new URL(`/client/rooms/${sharedRoomId}`, window.location.origin); url.hash = new URLSearchParams({ invite: result.inviteToken }).toString(); setInviteHref(url.href); setJoinCode(result.joinCode); })} onCopyLink={() => void navigator.clipboard.writeText(inviteHref).then(() => setNotice("Invitation copied. Share it when you’re ready.")).catch(() => setError("Select and copy the room code instead."))} onCopyCode={() => void navigator.clipboard.writeText(joinCode).then(() => setNotice("Room code copied.")).catch(() => setError("Select and copy the code shown here."))} />}
          <section className="home-conversation" aria-label="Shared conversation"><h3>Conversation</h3>{conversation.length === 0 && <p>Tell each other what matters. Ask the assistant when you want a design change.</p>}<ol>{conversation.map(item => item.kind === "person" ? <li key={item.id} data-role={item.role}><strong>{item.role === shared.role ? `You · ${prettyName(item.role)}` : prettyName(item.role)}</strong><p>{item.text}</p></li> : <li key={item.id} data-role="assistant" data-request-id={item.requestId} data-revision-id={item.revisionId}><strong><Sparkles size={14} aria-hidden="true" />{shared.assistant.name} · Assistant</strong><p>{item.text}</p>{item.changes.length > 0 && <ul>{item.changes.map((change, index) => <li key={index}>{change}</li>)}</ul>}<span className="home-reply-source">{item.provider === "fixture" ? "Local test response · Gemini not connected" : "Generated with Gemini"}{item.status === "conflict" ? " · preserved conflicting option" : " · design saved"}</span><Button variant="ghost" disabled={working} onClick={() => void inspectRevision(item.revisionId)}>View saved design<ArrowRight size={14} aria-hidden="true" /></Button></li>)}</ol><form onSubmit={event => { event.preventDefault(); if (!message.trim() || !head) return; const input = message.trim(); void run("Sending message", async () => { const result = await api.request<SharedHome>(`${sharedPath}/messages`, { text: input, requestId: requestId(`message:${input}`), askAssistant: false, baseRevisionId: head, selection }); accept(result); setMessage(""); setNotice("Message saved for both of you."); }); }}><label className="home-field"><span>Message</span><Textarea aria-label="Message" value={message} onChange={event => setMessage(event.target.value)} maxLength={1000} rows={3} placeholder="What would make this home feel right?" /></label><div className="home-message-actions"><Button variant="outline" type="submit" disabled={!message.trim() || !!busy}><Send size={15} aria-hidden="true" />Send message</Button><Button type="button" disabled={!message.trim() || working || unresolvedGeneration || !!comparison} onClick={() => { if (!head) return; const input = message.trim(); void run("Assistant is designing", async () => { const attempt: PendingDesign = { origin: "chat", prompt: input, selection: structuredClone(selection), baseRevisionId: head, requestId: requestId(`ask:${input}:${JSON.stringify(selection)}`) }; rememberAttempt(attempt); const result = await api.request<SharedHome>(`${sharedPath}/messages`, { text: input, requestId: attempt.requestId, askAssistant: true, baseRevisionId: head, selection: attempt.selection }); accept(result); ensureFinished(result); rememberAttempt(null); setMessage(""); setNotice("Your assistant’s saved design is ready for both of you."); }); }}><Sparkles size={15} aria-hidden="true" />Ask assistant</Button></div></form></section>
          <section className="home-decisions"><h3>Agree on this design</h3><div className="home-decision-version" id="decision-design-version"><strong>{designVersion(current, head ?? null)}</strong>{currentRevision && <time dateTime={currentRevision.createdAt}>Saved {new Date(currentRevision.createdAt).toLocaleString("en-IN")}</time>}{comparison && <p>Return to the current design before making a decision.</p>}</div><p>Both decisions refer to the exact saved version. Further design changes need fresh decisions.</p><ol><li><span className={shared.acceptedRevisionId === head ? "is-confirmed" : ""}>{shared.acceptedRevisionId === head ? <Check size={16} aria-hidden="true" /> : "1"}</span>Client accepts the design</li><li><span className={shared.approvedRevisionId === head ? "is-confirmed" : ""}>{shared.approvedRevisionId === head ? <Check size={16} aria-hidden="true" /> : "2"}</span>Designer approves the design</li></ol>{shared.role === "client" && <Button aria-describedby="decision-design-version" disabled={!shared.canAccept || working || !!comparison} onClick={() => void run("Saving design acceptance", async () => { const result = await api.request<SharedHome>(`${sharedPath}/accept`, { revisionId: head, requestId: requestId("accept") }); accept(result); setNotice("Your acceptance is saved for this design version."); })}>Accept this design</Button>}{shared.role === "designer" && <Button aria-describedby="decision-design-version" disabled={!shared.canApprove || working || !!comparison} onClick={() => void run("Saving design approval", async () => { const result = await api.request<SharedHome>(`${sharedPath}/approve`, { revisionId: head, requestId: requestId("approve") }); accept(result); setNotice("Your design approval is saved."); })}>Approve this design</Button>}<p className="home-small">Design agreement is a review decision, not a legal signature or authorization to begin work.</p><Button variant="outline" disabled={!shared.canGenerateAgreement || working || !!comparison} onClick={() => void run("Preparing draft agreement", async () => { const result = await api.request<SharedHome>(`${sharedPath}/agreements`, { revisionId: head, requestId: requestId("agreement") }); accept(result); ensureFinished(result); setNotice("Draft agreement saved in your shared library."); })}>Generate draft agreement</Button></section>
          <section className="home-agreement-library"><h3>Shared agreement library</h3>{shared.agreements.length ? shared.agreements.map((agreement, index) => <article key={agreement.id}><span>Draft agreement · version {index + 1}</span><h4>{agreement.title}</h4><p className="home-agreed-version">{designVersion(current, agreement.revisionId)}</p><time className="home-agreement-date" dateTime={agreement.createdAt}>Agreement saved {new Date(agreement.createdAt).toLocaleString("en-IN")}</time><p>{agreement.revisionId === head ? "Matches the current design" : "Preserved earlier design agreement"}</p><Button variant="outline" disabled={!!busy} onClick={() => void run("Preparing agreement download", async () => download(new Blob([await api.request<string>(`${sharedPath}/agreements/${agreement.id}/export`, undefined, true)], { type: "text/markdown" }), `${agreement.title}.md`))}>Download agreement</Button><Button variant="ghost" disabled={working} onClick={() => void inspectRevision(agreement.revisionId, true)}>View agreed design<ArrowRight size={15} aria-hidden="true" /></Button><details><summary>Read agreement</summary><div className="home-agreement-text">{agreement.markdown}</div></details></article>) : <p>Your draft agreements appear here after both people agree on a saved design.</p>}</section>
        </> : <p role="status">Opening the shared home…</p>}</TabsContent>
      </Tabs></aside>
      {sharedRoomId && panel !== "share" && <Button className="home-conversation-shortcut" variant="outline" onClick={() => setPanel("share")}>Conversation & decisions<ChevronRight size={16} aria-hidden="true" /></Button>}
    </main><div hidden><HousePlan document={scene} svgRef={exportSvg} /></div>
  </div>;
}
