import { test, expect, identity, apiHome, fixtureHealth, origin, requestId } from './helpers';

test.beforeEach(async ({ request }) => fixtureHealth(request));
test('API access and revision publication preserve owner scope, deduplication and conflicts', async ({ request }, info) => {
  const owner = await identity(request), stranger = await identity(request);
  expect((await request.get(origin + '/api/homes')).status()).toBe(401);
  const home = await apiHome(request, owner);
  expect((await (await request.get(origin + '/api/homes', { headers: stranger })).json()).homes).toEqual([]);
  expect((await request.get(origin + '/api/homes/' + home.id, { headers: stranger })).status()).toBe(404);
  expect((await request.get(origin + '/api/homes/' + home.id + '/export?revisionId=' + home.headRevisionId, { headers: stranger })).status()).toBe(404);
  const room = home.scene!.rooms[0];
  const baseRevisionId = home.headRevisionId;
  const material = home.scene!.materials.find(item => item.id !== room.floorMaterialId)!;
  const patch = { schemaVersion: 2, operations: [{ op: 'setMaterial', entityId: room.id, surface: 'floor', materialId: material.id }] };
  const payload = { baseRevisionId, requestId: requestId(), selection: { kind: 'surface', entityId: room.id, surface: 'floor' }, patch };
  const saved = await request.post(origin + '/api/homes/' + home.id + '/revisions', { headers: owner, data: payload });
  expect(saved.ok()).toBe(true);
  const next = (await saved.json()).home;
  expect(next.headRevisionId).not.toBe(baseRevisionId);
  const duplicate = await request.post(origin + '/api/homes/' + home.id + '/revisions', { headers: owner, data: payload });
  expect(duplicate.ok()).toBe(true);
  expect((await duplicate.json()).home.headRevisionId).toBe(next.headRevisionId);
  const stale = await request.post(origin + '/api/homes/' + home.id + '/revisions', { headers: owner, data: { ...payload, requestId: requestId() } });
  expect(stale.ok()).toBe(true);
  const conflict = (await stale.json()).home;
  expect(conflict.headRevisionId).toBe(next.headRevisionId);
  expect(conflict.revisions).toHaveLength(next.revisions.length + 1);
  expect(conflict.revisions.at(-1).conflict).toBe(true);
  const refused = await request.post(origin + '/api/homes/' + home.id + '/revisions', { headers: stranger, data: { ...payload, baseRevisionId: next.headRevisionId, requestId: requestId() } });
  expect(refused.status()).toBe(404);
  const wrongScope = await request.post(origin + '/api/homes/' + home.id + '/revisions', { headers: owner, data: { ...payload, baseRevisionId: next.headRevisionId, requestId: requestId(), selection: { kind: 'room', roomId: home.scene!.rooms[1].id } } });
  expect(wrongScope.status()).toBeGreaterThanOrEqual(400);
  expect(wrongScope.status()).toBeLessThan(500);
  const after = (await (await request.get(origin + '/api/homes/' + home.id, { headers: owner })).json()).home;
  expect(after.headRevisionId).toBe(next.headRevisionId);
  expect(after.scene).toEqual(next.scene);
  await info.attach('revision-security', { body: JSON.stringify({ duplicatePreservedHead: true, staleVersionPreservedAsConflict: true, strangerStatus: refused.status(), invalidScopeStatus: wrongScope.status(), revisions: after.revisions.length }), contentType: 'application/json' });
});

test('shared design decisions enforce roles and become ineligible after another saved edit', async ({ request }, info) => {
  const designer = await identity(request), client = await identity(request), stranger = await identity(request);
  const home = await apiHome(request, designer);
  const assistant = await request.post(origin + '/api/design-assistants', { headers: designer, data: { requestId: requestId() } });
  expect(assistant.ok()).toBe(true);
  const opened = await request.post(origin + '/api/homes/' + home.id + '/room', { headers: designer, data: { requestId: requestId(), assistantId: (await assistant.json()).assistant.id } });
  expect(opened.ok()).toBe(true);
  const shared = await opened.json();
  const roomId = shared.room.id;
  const prefix = origin + '/api/rooms/' + roomId + '/home';
  const joined = await request.post(origin + '/api/rooms/join', { headers: client, data: { joinCode: shared.joinCode } });
  expect(joined.ok()).toBe(true);
  expect((await request.get(prefix, { headers: stranger })).status()).toBe(404);
  expect((await request.get(origin + '/api/homes/' + home.id, { headers: client })).status()).toBe(404);
  const decide = (headers: Record<string, string>, action: string, revisionId = home.headRevisionId) => request.post(prefix + '/' + action, { headers, data: { requestId: requestId(), revisionId } });
  expect((await decide(designer, 'accept')).status()).toBe(403);
  expect((await decide(client, 'approve')).status()).toBe(403);
  expect((await decide(client, 'agreements')).status()).toBe(403);
  expect((await decide(designer, 'approve')).status()).toBe(409);
  expect((await decide(client, 'accept')).ok()).toBe(true);
  expect((await decide(designer, 'approve')).ok()).toBe(true);
  const authorized = await (await request.get(prefix, { headers: designer })).json();
  expect(authorized.canGenerateAgreement).toBe(true);
  const changed = await request.post(prefix + '/revisions', { headers: client, data: { requestId: requestId(), baseRevisionId: home.headRevisionId, selection: { kind: 'surface', entityId: 'living', surface: 'floor' }, patch: { schemaVersion: 2, operations: [{ op: 'setMaterial', entityId: 'living', surface: 'floor', materialId: 'wood-dark' }] } } });
  expect(changed.ok()).toBe(true);
  const latest = await changed.json();
  expect(latest.home.headRevisionId).not.toBe(home.headRevisionId);
  const stale = await (await request.get(prefix, { headers: designer })).json();
  expect(stale.canGenerateAgreement).toBe(false);
  expect(stale.canApprove).toBe(false);
  expect(stale.decisions).toHaveLength(2);
  expect((await decide(designer, 'approve')).status()).toBe(409);
  expect((await decide(designer, 'agreements')).status()).toBe(409);
  expect((await decide(client, 'accept', latest.home.headRevisionId)).ok()).toBe(true);
  expect((await decide(designer, 'approve', latest.home.headRevisionId)).ok()).toBe(true);
  const payload = { requestId: requestId(), revisionId: latest.home.headRevisionId };
  const agreementResponse = await request.post(prefix + '/agreements', { headers: designer, data: payload });
  expect(agreementResponse.ok()).toBe(true);
  const agreed = await agreementResponse.json();
  expect(agreed.agreements).toHaveLength(1);
  expect(agreed.agreements[0]).toMatchObject({ revisionId: latest.home.headRevisionId, status: 'draft', provider: 'fixture' });
  const again = await request.post(prefix + '/agreements', { headers: designer, data: payload });
  expect(again.ok()).toBe(true);
  expect((await again.json()).agreements).toEqual(agreed.agreements);
  const exported = await request.get(prefix + '/agreements/' + agreed.agreements[0].id + '/export', { headers: client });
  expect(exported.ok()).toBe(true);
  expect(await exported.text()).toContain(latest.home.headRevisionId);
  expect((await request.get(prefix + '/agreements/' + agreed.agreements[0].id + '/export', { headers: stranger })).status()).toBe(404);
  await info.attach('shared-role-and-stale-decision-proof', { body: JSON.stringify({ roleDenials: 3, oldDecisionsPreserved: stale.decisions.length, currentAgreementCount: agreed.agreements.length, currentRevision: latest.home.headRevisionId, agreementStatus: 'draft' }), contentType: 'application/json' });
});
