import { homeTemplates } from '@vibeestimate/scene-core';
import { test, expect, accessible, capture, fixtureHealth, geometry, downloadedText, downloadedPlan } from './helpers';
import { createHome, generate, selectArea } from './ui';
import { openSharedHome, askInRoom, agreeAndDownload } from './shared-ui';
import { pixelDifference } from '../spatial/browser/png';

test.beforeEach(async ({ request }) => fixtureHealth(request));

test('Flow 1 — create a project, choose every home and let AI fill the design', async ({ page }, info) => {
  test.setTimeout(360000);
  for (const template of homeTemplates) {
    const original = await createHome(page, template.id);
    const resources = await page.evaluate(() => ({ encodedBytes: (performance.getEntriesByType('resource') as PerformanceResourceTiming[]).reduce((sum, resource) => sum + resource.encodedBodySize, 0), readyObservedMs: Math.round(performance.now()) }));
    expect(resources.encodedBytes).toBeLessThan(info.project.name === 'desktop' ? 5_000_000 : 3_000_000);
    await info.attach(template.id + '-first-view-resources', { body: JSON.stringify(resources), contentType: 'application/json' });
    const designed = await generate(page, template.prompts[0]);
    expect(designed.headRevisionId).not.toBe(original.headRevisionId);
    expect(designed.title.trim()).not.toBe('');
    expect(designed.brief?.summary.trim()).not.toBe('');
    expect(designed.brief?.source).toBe('fixture');
    expect(designed.scene!.rooms).toHaveLength(template.document.rooms.length);
    expect(designed.scene).not.toEqual(original.scene);
    const actual = await geometry(page);
    for (const item of designed.scene!.instances) {
      const box = actual.entities[item.id];
      expect(box, 'The actual GLB must exist for ' + item.id).toBeTruthy();
      expect(box.position).toEqual(item.position.map(value => value / 1000));
      const angle = item.rotation * Math.PI / 180;
      const expectedWidth = (Math.abs(Math.cos(angle)) * item.dimensions[0] + Math.abs(Math.sin(angle)) * item.dimensions[2]) / 1000;
      const expectedDepth = (Math.abs(Math.sin(angle)) * item.dimensions[0] + Math.abs(Math.cos(angle)) * item.dimensions[2]) / 1000;
      expect(box.max[0] - box.min[0]).toBeCloseTo(expectedWidth, 2);
      expect(box.max[1] - box.min[1]).toBeCloseTo(item.dimensions[1] / 1000, 2);
      expect(box.max[2] - box.min[2]).toBeCloseTo(expectedDepth, 2);
    }
    await capture(page, info, template.id + '-generated-overview');
    await page.getByRole('button', { name: 'Plan', exact: true }).click();
    await capture(page, info, template.id + '-plan', false);
    await accessible(page);
    await page.getByRole('button', { name: 'Overview', exact: true }).click();
    const url = page.url();
    await page.reload();
    await expect(page).toHaveURL(url);
    const reopened = await geometry(page);
    expect(reopened.documentId).toBe(designed.scene!.id);
    expect(Object.values(reopened.entities).filter(item => item.type === 'wall')).toHaveLength(designed.scene!.walls.length);
  }
});

test('Flow 2 — light the complete home and inspect the real interior', async ({ page }, info) => {
  const original = await createHome(page);
  const originalLights = original.scene!.instances.filter(item => item.light).length;
  const designed = await generate(page, 'Add warm ceiling lights throughout the home.');
  const added = designed.scene!.instances.filter(item => item.light && !original.scene!.instances.some(before => before.id === item.id));
  expect(added.length).toBeGreaterThan(0);
  const rendered = await geometry(page);
  expect(Object.keys(rendered.lights).length).toBeGreaterThan(originalLights);
  for (const light of added) {
    expect(rendered.lights[light.id].intensity).toBeGreaterThan(0);
    expect(rendered.lights[light.id].position[1]).toBeGreaterThan(2);
  }
  await page.getByRole('button', { name: 'Evening', exact: true }).click();
  await page.getByRole('button', { name: 'Inside', exact: true }).click();
  await capture(page, info, 'warm-lights-inside');
  expect((await geometry(page)).camera[1]).toBeCloseTo(1.6, 2);
  const selectedLight = added.find(item => item.roomId === 'living') ?? added[0];
  await page.getByRole('tab', { name: 'Edit', exact: true }).click();
  await page.getByLabel('Edit selection', { exact: true }).selectOption('object:' + selectedLight.id);
  const beforeSwitch = await geometry(page);
  const on = await page.locator('.home-canvas canvas').screenshot({ path: info.outputPath('selected-light-on.png') });
  await page.getByLabel('Light enabled', { exact: true }).uncheck();
  await page.getByRole('button', { name: 'Apply light settings', exact: true }).click();
  await expect.poll(async () => (await geometry(page)).lights[selectedLight.id].intensity).toBe(0);
  const switched = await geometry(page);
  for (const [id, light] of Object.entries(beforeSwitch.lights)) if (id !== selectedLight.id) expect(switched.lights[id]).toEqual(light);
  expect(switched.camera).toEqual(beforeSwitch.camera);
  const off = await page.locator('.home-canvas canvas').screenshot({ path: info.outputPath('selected-light-off.png') });
  const difference = pixelDifference(on, off);
  expect(difference.meanRgbDifference).toBeGreaterThan(1);
  await info.attach('actual-light-pixel-difference', { body: JSON.stringify(difference), contentType: 'application/json' });
  await page.getByRole('button', { name: 'Undo', exact: true }).click();
  await expect.poll(async () => (await geometry(page)).lights[selectedLight.id].intensity).toBe(beforeSwitch.lights[selectedLight.id].intensity);
  await page.getByRole('button', { name: 'Redo', exact: true }).click();
  await expect.poll(async () => (await geometry(page)).lights[selectedLight.id].intensity).toBe(0);
  await page.getByRole('button', { name: 'Undo', exact: true }).click();
  await expect.poll(async () => (await geometry(page)).lights[selectedLight.id].intensity).toBe(beforeSwitch.lights[selectedLight.id].intensity);
  await page.getByRole('button', { name: 'Overview', exact: true }).click();
  await capture(page, info, 'whole-home-lighting');
  await accessible(page);
});

test('Flow 3 — refine a living room while every neighbouring room stays intact', async ({ page }, info) => {
  const original = await createHome(page);
  await selectArea(page, 'room:living');
  const designed = await generate(page, 'Use a smaller table and warm finishes in this room, keeping the doorway clear.');
  expect(designed.scene).not.toEqual(original.scene);
  for (const item of original.scene!.instances.filter(item => item.roomId !== 'living')) expect(designed.scene!.instances.find(next => next.id === item.id)).toEqual(item);
  expect(designed.scene!.openings).toEqual(original.scene!.openings);
  for (const room of original.scene!.rooms.filter(room => room.id !== 'living')) expect(designed.scene!.rooms.find(next => next.id === room.id)).toEqual(room);
  await capture(page, info, 'selected-living-room');
  const report = await geometry(page);
  const table = designed.scene!.instances.find(item => item.catalogId === 'table' && item.roomId === 'living');
  if (table && table.rotation === 0) expect(report.entities[table.id].max[0] - report.entities[table.id].min[0]).toBeCloseTo(table.dimensions[0] / 1000, 2);
  const sofa = designed.scene!.instances.find(item => item.catalogId === 'sofa' && item.roomId === 'living')!;
  await page.getByRole('tab', { name: 'Edit', exact: true }).click();
  await page.getByLabel('Edit selection', { exact: true }).selectOption('object:' + sofa.id);
  await page.getByText('Position and size', { exact: true }).click();
  await page.getByLabel('Position X (mm)', { exact: true }).fill(String(table!.position[0]));
  await page.getByLabel('Position Z (mm)', { exact: true }).fill(String(table!.position[2]));
  await page.getByRole('button', { name: 'Apply position', exact: true }).click();
  await expect(page.getByRole('main').getByRole('alert')).toContainText('collision');
  expect((await geometry(page)).entities[sofa.id].position).toEqual(report.entities[sofa.id].position);
  await capture(page, info, 'collision-rejected-with-neighbours-intact');
  await accessible(page);
});

test('Flow 4 — change one wall face with AI and preserve the other side', async ({ page }, info) => {
  const original = await createHome(page);
  const wall = original.scene!.walls.find(item => item.frontRoomId === 'living' && item.backRoomId)!;
  expect(wall).toBeTruthy();
  await selectArea(page, 'surface:' + wall.id + ':front');
  const before = await geometry(page);
  const designed = await generate(page, 'Make this wall warm clay and keep the rest as it is.');
  const next = designed.scene!.walls.find(item => item.id === wall.id)!;
  expect(next.frontMaterialId).not.toBe(wall.frontMaterialId);
  expect(next.backMaterialId).toBe(wall.backMaterialId);
  expect(designed.scene!.walls.filter(item => item.id !== wall.id)).toEqual(original.scene!.walls.filter(item => item.id !== wall.id));
  expect(designed.scene!.instances).toEqual(original.scene!.instances);
  const after = await geometry(page);
  expect(after.wallFaces[wall.id].front.color).not.toBe(before.wallFaces[wall.id].front.color);
  expect(after.wallFaces[wall.id].back.color).toBe(before.wallFaces[wall.id].back.color);
  await capture(page, info, 'one-wall-face');
  await page.getByRole('tab', { name: 'Edit', exact: true }).click();
  await page.getByLabel('Material', { exact: true }).selectOption('paint-sage');
  await page.getByRole('button', { name: 'Apply material', exact: true }).click();
  await expect.poll(async () => (await geometry(page)).wallFaces[wall.id].front.color).toBe(designed.scene!.materials.find(item => item.id === 'paint-sage')!.color);
  expect((await geometry(page)).wallFaces[wall.id].back.color).toBe(before.wallFaces[wall.id].back.color);
  await page.getByRole('button', { name: 'Plan', exact: true }).click();
  await capture(page, info, 'wall-selection-plan', false);
  await accessible(page);
});

test('Flow 5 — recover from an unavailable model, compare options and reopen the saved design', async ({ page }, info) => {
  const original = await createHome(page);
  const before = await geometry(page);
  await page.getByRole('tab', { name: 'Options', exact: true }).click();
  const originalPlan = await downloadedPlan(page, info, 'original-floor-plan.png');
  expect(originalPlan.filename).toContain('-design-v1-floor-plan.png');
  await page.getByRole('tab', { name: 'Design', exact: true }).click();
  await page.route('**/api/homes/*/generate', route => route.fulfill({ status: 503, contentType: 'application/json', body: JSON.stringify({ error: { code: 'AI_UNAVAILABLE', message: 'Design generation is temporarily unavailable. Your saved design is unchanged.' } }) }), { times: 1 });
  await page.getByLabel('Describe your design', { exact: true }).fill('Add warm ceiling lights throughout the home.');
  await page.getByRole('button', { name: 'Generate design', exact: true }).click();
  await expect(page.getByRole('main').getByRole('alert')).toContainText('unavailable');
  expect((await geometry(page)).entities).toEqual(before.entities);
  await capture(page, info, 'generation-failure-preserves-design');
  const designed = await generate(page, 'Add warm ceiling lights throughout the home.');
  await page.getByRole('tab', { name: 'Options', exact: true }).click();
  await page.getByRole('button', { name: 'Compare starting layout', exact: true }).click();
  const baseline = await geometry(page);
  expect(Object.keys(baseline.lights)).toHaveLength(original.scene!.instances.filter(item => item.light).length);
  await capture(page, info, 'starting-layout-comparison');
  const historicalPlan = await downloadedPlan(page, info, 'historical-floor-plan.png');
  expect(historicalPlan.filename).toContain('-design-v1-floor-plan.png');
  expect(historicalPlan.pixels.equals(originalPlan.pixels), 'A historical PNG must reproduce the original plan pixels.').toBe(true);
  await page.getByRole('button', { name: 'Return to current design', exact: true }).click();
  const current = await geometry(page);
  expect(Object.keys(current.lights)).toHaveLength(designed.scene!.instances.filter(item => item.light).length);
  expect(current.camera).toEqual(baseline.camera);
  await page.reload();
  await expect(page.getByText('Saved', { exact: true })).toBeVisible();
  expect(Object.keys((await geometry(page)).lights)).toHaveLength(designed.scene!.instances.filter(item => item.light).length);
  await capture(page, info, 'saved-option-reopened');
  const disposals = await page.evaluate(() => window.__houseLifecycle?.disposals ?? 0);
  await page.getByRole('link', { name: 'Your homes', exact: true }).click();
  await expect(page.getByRole('heading', { name: 'Your homes', exact: true })).toBeVisible();
  await expect.poll(() => page.evaluate(() => window.__houseLifecycle?.disposals ?? 0)).toBeGreaterThan(disposals);
  await page.getByRole('link').filter({ has: page.getByRole('heading', { name: designed.title, exact: true }) }).click();
  expect(Object.keys((await geometry(page)).lights)).toHaveLength(designed.scene!.instances.filter(item => item.light).length);
  await page.getByRole('tab', { name: 'Options', exact: true }).click();
  await page.getByRole('button', { name: 'Prepare design summary', exact: true }).click();
  await expect(page.getByRole('button', { name: 'Download design summary', exact: true })).toBeEnabled();
  const summary = await downloadedText(page, 'Download design summary', info, 'design-summary.md');
  expect(summary).toContain(designed.headRevisionId!);
  expect(summary.toLowerCase()).toContain('assum');
  const currentPlan = await downloadedPlan(page, info, 'saved-floor-plan.png');
  expect(currentPlan.filename).toContain('-design-v2-floor-plan.png');
  expect(currentPlan.pixels.equals(originalPlan.pixels), 'The generated lights must appear in the current plan export.').toBe(false);
  await info.attach('historical-png-proof', { body: JSON.stringify({ dimensions: [1600, 1200], originalRevision: original.headRevisionId, currentRevision: designed.headRevisionId, historicalPixelsMatchOriginal: true, currentPixelsDiffer: true }), contentType: 'application/json' });
  await accessible(page);
});

test('Flow 6 — designer and client shape one home, accept its revision and leave with a shared draft agreement', async ({ page }, info) => {
  // Recorded Linux software rendering exhausted the six-minute whole-story
  // budget during its final edit. Keep each action/assertion bounded while
  // allowing both participants, downloads and historical reopening to finish.
  test.setTimeout(480000);
  const original = await createHome(page);
  const { clientPage, roomId, separateIdentities } = await openSharedHome(page);
  await page.getByLabel('Message', { exact: true }).fill('Let’s make this a warm home with room to gather.');
  const sendingMessage = page.waitForResponse(response => response.url().endsWith('/home/messages') && response.request().method() === 'POST' && response.request().postDataJSON()?.askAssistant === false);
  await page.getByRole('button', { name: 'Send message', exact: true }).click();
  const sentMessage = await sendingMessage;
  expect(sentMessage.ok()).toBe(true);
  expect((await sentMessage.json()).room.messages.some((message: { role: string; text: string }) => message.role === 'designer' && message.text === 'Let’s make this a warm home with room to gather.')).toBe(true);
  await clientPage.bringToFront();
  await expect(clientPage.getByText('Let’s make this a warm home with room to gather.', { exact: true })).toBeVisible();
  const lighting = await askInRoom(clientPage, 'Add warm ceiling lights throughout the home.');
  const expectedLights = lighting.home.scene!.instances.filter(item => item.light).length;
  expect(expectedLights).toBeGreaterThan(original.scene!.instances.filter(item => item.light).length);
  await expect.poll(async () => Object.keys((await geometry(page)).lights).length).toBe(expectedLights);
  await capture(clientPage, info, 'client-ai-lights');
  await page.bringToFront();
  await selectArea(page, 'room:living');
  const refined = await askInRoom(page, 'Use a smaller table in this living room.');
  expect(refined.home.headRevisionId).not.toBe(lighting.home.headRevisionId);
  const table = refined.home.scene!.instances.find(item => item.catalogId === 'table' && item.roomId === 'living')!;
  await expect.poll(async () => { const box = (await geometry(clientPage)).entities[table.id]; return box.max[0] - box.min[0]; }).toBeCloseTo(table.dimensions[0] / 1000, 2);
  await capture(page, info, 'designer-ai-refinement');
  const saved = await agreeAndDownload(page, clientPage, info);
  expect(saved.agreements[0].provider).toBe('fixture');
  expect(saved.agreements[0].revisionId).toBe(refined.home.headRevisionId);
  await capture(clientPage, info, 'client-agreement-library');
  await accessible(clientPage);
  await page.bringToFront();
  await page.reload();
  await geometry(page);
  await page.getByRole('tab', { name: 'Together', exact: true }).click();
  await expect(page.getByRole('button', { name: 'Download agreement', exact: true })).toBeEnabled();
  await capture(page, info, 'designer-reopened-shared-agreement');
  await accessible(page);
  // A later manual change needs fresh decisions; the saved agreement must still
  // open its exact earlier scene rather than silently showing the new head.
  const wall = refined.home.scene!.walls.find(item => item.frontRoomId === 'living' && item.backRoomId)!;
  const agreedMaterial = refined.home.scene!.materials.find(item => item.id === wall.frontMaterialId)!.color;
  await page.getByRole('tab', { name: 'Edit', exact: true }).click();
  await page.getByLabel('Edit selection', { exact: true }).selectOption('front:' + wall.id);
  const different = refined.home.scene!.materials.find(item => item.id.startsWith('paint-') && item.id !== wall.frontMaterialId)!;
  await page.getByLabel('Material', { exact: true }).selectOption(different.id);
  const changing = page.waitForResponse(response => response.url().endsWith('/home/revisions') && response.request().method() === 'POST');
  await page.getByRole('button', { name: 'Apply material', exact: true }).click();
  const changed = await changing;
  expect(changed.ok()).toBe(true);
  const later = await changed.json();
  expect(later.home.headRevisionId).not.toBe(saved.agreements[0].revisionId);
  expect(later.canGenerateAgreement).toBe(false);
  await expect.poll(async () => (await geometry(page)).wallFaces[wall.id].front.color).toBe(different.color);
  await page.getByRole('tab', { name: 'Together', exact: true }).click();
  await expect(page.getByText('Preserved earlier design agreement', { exact: true })).toBeVisible();
  const openingAgreed = page.waitForResponse(response => response.url().endsWith('/home/revisions/' + saved.agreements[0].revisionId));
  await page.getByRole('button', { name: 'View agreed design', exact: true }).click();
  const agreedResponse = await openingAgreed;
  expect(agreedResponse.ok()).toBe(true);
  expect((await agreedResponse.json()).revision.scene).toEqual(refined.home.scene);
  await expect.poll(async () => (await geometry(page)).wallFaces[wall.id].front.color).toBe(agreedMaterial);
  await capture(page, info, 'exact-agreed-design-after-later-edit');
  await page.getByRole('button', { name: 'Return to current design', exact: true }).click();
  await expect.poll(async () => (await geometry(page)).wallFaces[wall.id].front.color).toBe(different.color);
  await info.attach('collaborative-value-proof', { body: JSON.stringify({ roomId, separateIdentities, designRequestCount: 2, clientRevision: lighting.home.headRevisionId, chosenRevision: refined.home.headRevisionId, agreementId: saved.agreements[0].id, agreementSource: 'fixture', agreementStatus: 'draft' }), contentType: 'application/json' });
  await clientPage.close();
  await clientPage.video()?.saveAs(info.outputPath('flow-6-client.webm'));
});
