import fs from "node:fs";
import path from "node:path";
import { createRequire } from "node:module";
import { localEnv, root } from "./local-env.mjs";
import { completion, nodeChild } from "./processes.mjs";

const env = localEnv();
fs.mkdirSync(path.join(root, ".codex"), { recursive: true });
const q = value => JSON.stringify(value.replaceAll("\\", "/"));
const config = [
  "# Generated by npm run setup. Project-local only; no credentials.",
  ...["playwright", "shadcn"].flatMap(name => [
    "[mcp_servers." + name + "]",
    "command = " + q(process.execPath),
    "args = [" + q(path.join(root, "scripts/start-" + name + "-mcp.mjs")) + "]",
    "cwd = " + q(root),
    "startup_timeout_sec = 60",
    "tool_timeout_sec = 60",
    ""
  ])
].join("\n");
const configPath = path.join(root, ".codex/config.toml");
if (fs.existsSync(configPath) && !fs.readFileSync(configPath, "utf8").startsWith("# Generated by npm run setup.")) {
  throw new Error("Existing project MCP config is not managed by setup. Merge config.toml.example manually; refusing overwrite.");
}
fs.writeFileSync(configPath, config);
const mcpPath = path.join(root, ".mcp.json");
const existing = fs.existsSync(mcpPath) ? JSON.parse(fs.readFileSync(mcpPath, "utf8")) : {};
existing.mcpServers ??= {};
for (const name of ["playwright", "shadcn"]) {
  const launcher = path.join(root, "scripts/start-" + name + "-mcp.mjs");
  const previous = existing.mcpServers[name];
  if (previous && !previous.args?.some(arg => arg.replaceAll("\\", "/").endsWith("scripts/start-" + name + "-mcp.mjs"))) {
    throw new Error("Existing " + name + " MCP entry is not managed by setup; refusing overwrite.");
  }
  existing.mcpServers[name] = { command: process.execPath, args: [launcher] };
}
fs.writeFileSync(mcpPath, JSON.stringify(existing, null, 2) + "\n");
await completion(nodeChild("node_modules/@playwright/test/cli.js", ["install", "chromium"], env));
// MCP pins its own browser engine revision; install that browser locally too.
const require = createRequire(import.meta.url);
const mcpRequire = createRequire(require.resolve("@playwright/mcp/package.json"));
const mcpCli = path.join(path.dirname(mcpRequire.resolve("playwright/package.json")), "cli.js");
await completion(nodeChild(path.relative(root, mcpCli), ["install", "chromium"], env));
console.log("Project-local browsers and Playwright/shadcn MCP configuration ready. Reopen this repository in Codex to load the servers.");
